export type TemplateWordList = {
  id: string;
  name: string;
  description: string;
  words: string[];
};

export const TEMPLATE_WORD_LISTS: TemplateWordList[] = [
  {
    id: "template-general",
    name: "General High-Level Vocabulary",
    description: "Polished words for everyday clarity and precision.",
    words: [
      "abate",
      "adamant",
      "adept",
      "adroit",
      "ambivalent",
      "amiable",
      "anachronism",
      "austere",
      "belie",
      "benevolent",
      "candid",
      "capricious",
      "cogent",
      "concur",
      "conspicuous",
      "cursory",
      "deference",
      "diligent",
      "discern",
      "elusive",
      "empathetic",
      "endeavor",
      "engender",
      "erudite",
      "eschew",
      "exacting",
      "exemplary",
      "fervent",
      "flawed",
      "fortuitous",
      "frugal",
      "hinder",
      "impartial",
      "impeccable",
      "impetus",
      "inclined",
      "inevitable",
      "inherent",
      "innate",
      "insightful",
      "lucid",
      "meticulous",
      "nuance",
      "objective",
      "obsolete",
      "poignant",
      "pragmatic",
      "prolific",
      "resilient",
      "subtle",
      "tenuous",
      "vivid",
    ],
  },
  {
    id: "template-literary",
    name: "Literary and Rhetorical",
    description: "Elevated diction for literary and rhetorical expression.",
    words: [
      "allegory",
      "allusion",
      "anachronistic",
      "aphorism",
      "apposite",
      "arcane",
      "archetype",
      "assonance",
      "cadence",
      "chiaroscuro",
      "colloquy",
      "consonance",
      "catharsis",
      "didactic",
      "diaphanous",
      "diction",
      "dissonance",
      "elegiac",
      "ellipsis",
      "epigraph",
      "epithet",
      "euphony",
      "evocative",
      "fable",
      "figurative",
      "foreshadow",
      "genre",
      "hermetic",
      "hubris",
      "hyperbole",
      "imagery",
      "intertextual",
      "irony",
      "juxtapose",
      "laconic",
      "leitmotif",
      "metaphor",
      "metonymy",
      "motif",
      "narrative",
      "ode",
      "oxymoron",
      "paradox",
      "parody",
      "pathos",
      "pastiche",
      "persona",
      "rhetoric",
      "satire",
      "subtext",
      "synecdoche",
      "tenor",
      "trope",
    ],
  },
  {
    id: "template-politics",
    name: "Politics and Public Life",
    description: "Vocabulary for civic discourse and policy analysis.",
    words: [
      "advocacy",
      "amendment",
      "appeal",
      "authoritarian",
      "bipartisan",
      "bureaucracy",
      "caucus",
      "censure",
      "coalition",
      "consensus",
      "constituency",
      "constitutional",
      "deliberation",
      "diplomacy",
      "dissent",
      "electorate",
      "embargo",
      "enfranchise",
      "federalism",
      "filibuster",
      "fiscal",
      "governance",
      "hegemony",
      "incumbent",
      "inequality",
      "infrastructure",
      "jurisdiction",
      "legislation",
      "lobbyist",
      "mandate",
      "minority",
      "moderate",
      "multilateral",
      "partisan",
      "plebiscite",
      "policy",
      "populism",
      "pragmatism",
      "ratify",
      "referendum",
      "regulatory",
      "sanction",
      "sovereignty",
      "stewardship",
      "subsidy",
      "summit",
      "treaty",
      "unilateral",
      "veto",
      "welfare",
      "whip",
      "zealot",
    ],
  },
];
